volumes:
  weather_tracker:

services:

  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      HIBERNATE_CONNECTION_URL: jdbc:postgresql://db:5432/weather_tracker



  db:
    image: postgres:17
    container_name: weather_tracker_db
    environment:
      POSTGRES_DB: weather_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 7088
    ports:
      - "5433:5432"
    volumes:
      - weather_tracker:/var/lib/postgresql/data

